# none_dic = {'dt': {'no_sampler': {'no_pca': {'min_impurity_decrease': 1e-07},
#                                   'pca': {'min_impurity_decrease': 0.0001}},
#                    'rff': {'no_pca': {'min_impurity_decrease': 1e-06, 'gamma': 0.0001},
#                            'pca_first': {'min_impurity_decrease': 1e-10, 'gamma': 1e-05},
#                            'pca_last': {'min_impurity_decrease': 1e-05, 'gamma': 0.01}},
#                    'nystroem': {'no_pca': {'min_impurity_decrease': 0.001, 'gamma': 1e-05},
#                                 'pca_first': {'min_impurity_decrease': 1e-06, 'gamma': 0.0001},
#                                 'pca_last': {'min_impurity_decrease': 0.001, 'gamma': 0.1}}},
#             'logit': {'no_sampler': {'no_pca': {'C': 100}, 'pca': {'C': 1000}},
#                       'rff': {'no_pca': {'C': 1000, 'gamma': 0.01},
#                               'pca_first': {'C': 100, 'gamma': 0.1},
#                               'pca_last': {'C': 1000, 'gamma': 0.01}},
#                       'nystroem': {'no_pca': {'C': 1000, 'gamma': 0.01},
#                                    'pca_first': {'C': 1000, 'gamma': 0.1},
#                                    'pca_last': {'C': 1000, 'gamma': 0.01}}},
#             'linear_svc': {'no_sampler': {'no_pca': {'C': 1}, 'pca': {'C': 10}},
#                            'rff': {'no_pca': {'C': 100, 'gamma': 0.01},
#                                    'pca_first': {'C': 10, 'gamma': 0.1},
#                                    'pca_last': {'C': 100, 'gamma': 0.1}},
#                            'nystroem': {'no_pca': {'C': 10, 'gamma': 0.1},
#                                         'pca_first': {'C': 1000, 'gamma': 0.1},
#                                         'pca_last': {'C': 100, 'gamma': 0.1}}}}


def get_segment_none_dic():
    none_dic = {'dt': {'no_sampler': {'no_pca': {'min_impurity_decrease': 1e-07},
                                      'pca': {'min_impurity_decrease': 0.0001}},
                       'rff': {'no_pca': {'min_impurity_decrease': 1e-06, 'gamma': 0.0001},
                               'pca_first': {'min_impurity_decrease': 1e-10, 'gamma': 1e-05},
                               'pca_last': {'min_impurity_decrease': 1e-05, 'gamma': 0.01}},
                       'nystroem': {'no_pca': {'min_impurity_decrease': 0.001, 'gamma': 1e-05},
                                    'pca_first': {'min_impurity_decrease': 1e-06, 'gamma': 0.0001},
                                    'pca_last': {'min_impurity_decrease': 0.001, 'gamma': 0.1}}},
                'logit': {'no_sampler': {'no_pca': {'C': 100}, 'pca': {'C': 1000}},
                          'rff': {'no_pca': {'C': 1000, 'gamma': 0.01},
                                  'pca_first': {'C': 100, 'gamma': 0.1},
                                  'pca_last': {'C': 1000, 'gamma': 0.01}},
                          'nystroem': {'no_pca': {'C': 1000, 'gamma': 0.01},
                                       'pca_first': {'C': 1000, 'gamma': 0.1},
                                       'pca_last': {'C': 1000, 'gamma': 0.01}}},
                'linear_svc': {'no_sampler': {'no_pca': {'C': 1}, 'pca': {'C': 10}},
                               'rff': {'no_pca': {'C': 100, 'gamma': 0.01},
                                       'pca_first': {'C': 10, 'gamma': 0.1},
                                       'pca_last': {'C': 100, 'gamma': 0.1}},
                               'nystroem': {'no_pca': {'C': 10, 'gamma': 0.1},
                                            'pca_first': {'C': 1000, 'gamma': 0.1},
                                            'pca_last': {'C': 100, 'gamma': 0.1}}}}
    return none_dic
